apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: validate-image-signature
spec:
  validationFailureAction: enforce
  background: false
  webhookTimeoutSeconds: 30
  failurePolicy: Fail  
  rules:
    - name: require-signature
      match:
        any:
        - resources:
            kinds:
              - Pod
      verifyImages:
      - imageReferences:
        - "ghcr.io/janeczku/*:*"
        verifyDigest: false
        required: false
        mutateDigest: false
        attestors:
        - entries:
          - keyless:
              issuer: https://token.actions.githubusercontent.com
              subject: https://github.com/janeczku/cosign-example/.github/workflows/release.yaml@refs/heads/main
              rekor:
                url: https://rekor.sigstore.dev